Repository lsglab/frontend-sapper, pull requests merged in 2020-08, with the labels that each got.

#16 Solve flaws in the workflow automation process
  .github/auto_assign.yml
  .github/card-labeler.yml
  .github/workflows/on-approved.yml
  .github/workflows/on-branch.yml
  .github/workflows/on-comment.yml
  .github/workflows/on-opened.yml
  .github/workflows/on-pr.yml
Labels: Approved

#19 chore: Deleted auto-assign
  .github/auto_assign.yml
Labels: Approved

#24 feat(homepage): Add new homepage
  src/components/Nav.svelte
  src/routes/_layout.svelte
  src/routes/index.svelte
  static/global.css
Labels: In review

#45 chore: moved from automerge to probot
  .github/auto-merge.yml
  .github/workflows/on-push.yml
Labels: In progress
