Repository lsglab/frontend-sapper, pull requests merged in 2020-10, with the labels that each got.

#65 feat: Implement old layout
  README.md
  src/assets/media/arrow.svg
  src/assets/media/clock.svg
  src/assets/styles/components.scss
  src/components/Calender.svelte
  src/components/DashBackground.svelte
  src/components/Hero.svelte
  src/components/MensaImage.svelte
  src/components/Section.svelte
  src/components/common/Button.svelte
  src/components/common/ShadowImage.svelte
  src/components/common/Text.svelte
  src/components/sectionWrapper.svelte
  src/routes/article.svelte
  src/routes/index.svelte
  src/routes/mensa.svelte
  tailwind.config.js
  yarn.lock
Labels: In progress

#69 feat: Issue 66 add an error/404 page
  src/routes/_error.svelte
Labels: Approved

#67 ci: Added some apps and rules
  .github/auto-merge.yml
  .github/auto_assign.yml
  .github/card-labeler.yml
  .github/workflows/opened.yml
  .github/workflows/revert.yml
  .github/workflows/review.yml
Labels: in progress

#73 chore: Tweak the actions some more
  .github/CODEOWNERS
  .github/auto_assign.yml
  .github/workflows/opened.yml
  .github/workflows/revert.yml
  .github/workflows/review.yml
Labels: approved

#83 feat: Issue 77 new article
  README.md
  src/routes/article.svelte
Labels: approved

#84 feat: Issue 61 infopages and parents council
  src/assets/media/diamond-pattern.png
  src/assets/media/rect-pattern.png
  src/components/Carddeck.svelte
  src/components/Nav.svelte
  src/components/common/Card.svelte
  src/components/common/Link.svelte
  src/routes/_layout.svelte
  src/routes/information/[slug]-information.svelte
  src/routes/schoolfamily/[slug]-profile.svelte
  tailwind.config.js
Labels: in review

#86 feat: codewoners updated and nav removed
  .github/CODEOWNERS
  src/routes/_layout.svelte
Labels: approved
