Repository lsglab/frontend-sapper, pull requests merged in 2021-02, with the labels that each got.

#100 feat: improve the homepage design
  src/components/Awards.svelte
  src/components/Calender.svelte
  src/components/Section.svelte
  src/routes/artcollection.svelte
  src/routes/index.svelte
  tailwind.config.js
Labels: in progress

#103 feat: index.svelte now uses button and sectionWrapper component
  src/components/Hero.svelte
  src/components/common/Button.svelte
  src/components/common/Link.svelte
  src/components/sectionWrapper.svelte
  src/routes/_error.svelte
  src/routes/index.svelte
Labels: approved

#106 fix: removed media query usage by adding a custom breakpoint
  src/components/Section.svelte
  tailwind.config.js
Labels: ready for review

#107 feat: update subpages to match the landing page design
  src/components/Section.svelte
  src/components/common/Button.svelte
  src/components/common/Card.svelte
  src/components/common/Text.svelte
  src/routes/_error.svelte
  src/routes/article.svelte
  src/routes/schoolfamily/[slug].svelte
  tailwind.config.js
Labels: approved

#109 chore(codeowners): Remove codeowners
  .github/CODEOWNERS
Labels: approved

#112 feat: atomic design structure introduced
  src/components/Hero.svelte
  src/components/Scroll.svelte
  src/components/Styles.svelte
  src/components/Tailwind.svelte
  src/components/atoms/Button.svelte
  src/components/atoms/DashBackground.svelte
  src/components/atoms/Flex.svelte
  src/components/atoms/Grid.svelte
  src/components/atoms/Link.svelte
  src/components/atoms/MensaImage.svelte
  src/components/atoms/Section.svelte
  src/components/atoms/Styles.svelte
  src/components/atoms/Tailwind.svelte
  src/components/atoms/Text.svelte
  src/components/common/ShadowImage.svelte
  src/components/molecules/Awards.svelte
  src/components/molecules/Calender.svelte
  src/components/molecules/Card.svelte
  src/components/molecules/sectionWrapper.svelte
  src/components/organisms/Footer.svelte
  src/components/organisms/Hero.svelte
  src/components/organisms/Nav.svelte
  src/components/templates/Index.svelte
  src/components/templates/Mensa.svelte
  src/routes/_error.svelte
  src/routes/_layout.svelte
  src/routes/artcollection.svelte
  src/routes/article.svelte
  src/routes/index.svelte
  src/routes/information/[slug].svelte
  src/routes/mensa.svelte
  src/routes/schoolfamily/[slug].svelte
Labels: ready for review

#113 ci(auto-merge): Removed config
  .github/auto-merge.yml
Labels: in progress

#114 feat: Issue 111 update tailwind
  package.json
  src/components/atoms/DashBackground.svelte
  src/components/organisms/Hero.svelte
  src/routes/_error.svelte
  tailwind.config.js
  yarn.lock
Labels: ready for review

#116 feat: implemented new font size calculation
  src/assets/styles/typography.scss
  src/components/atoms/Button.svelte
  src/components/atoms/Text.svelte
  src/routes/_error.svelte
  src/routes/article.svelte
  tailwind.config.js
Labels: in progress

#119 fix: Issue 118 fix minor issues
  src/routes/_error.svelte
  src/routes/article.svelte
Labels: in progress

#117 feat: remake james nav using tailwind
  src/components/atoms/Section.svelte
  src/components/organisms/Hero.svelte
  src/components/organisms/Nav.svelte
  src/routes/_layout.svelte
  src/routes/article.svelte
  tailwind.config.js
Labels: ready for review

#121 feat: homepage is now displayed correctly on smaller screens
  src/assets/styles/typography.scss
  src/components/molecules/Awards.svelte
  src/components/molecules/Calender.svelte
  src/components/organisms/Hero.svelte
  src/components/organisms/Nav.svelte
  tailwind.config.js
Labels: ready for review
